### ISSUE TITLE
How do I run the tests?

### ISSUE THREAD

**Issue by Murii** [johnnyapol/libgdx-udp-extension#1]
I'm having problems running the tests.Any help?

**Comment by Unkn0wn0ne** [comment]
Hello.

I apologize for my absence. To run the tests you can build the project by linking the code against the core libgdx jars. Then you can run the tests either by launching them through an eclipse profile or by specifying the test classes as the main class argument.

Note: You must start the server test and then  the client test

**Comment by johnnyapol** [comment]
Closing this out as a rewrite is pending
